# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pantalla_generala.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QHeaderView, QLabel,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.dado1 = QLabel(self.centralwidget)
        self.dado1.setObjectName(u"dado1")
        self.dado1.setGeometry(QRect(10, 100, 91, 81))
        self.dado1.setMinimumSize(QSize(50, 50))
        self.dado1.setMaximumSize(QSize(100, 100))
        self.dado1.setScaledContents(True)
        self.dado2 = QLabel(self.centralwidget)
        self.dado2.setObjectName(u"dado2")
        self.dado2.setGeometry(QRect(10, 320, 91, 81))
        self.dado2.setScaledContents(True)
        self.dado3 = QLabel(self.centralwidget)
        self.dado3.setObjectName(u"dado3")
        self.dado3.setGeometry(QRect(230, 110, 101, 81))
        self.dado3.setScaledContents(True)
        self.dado4 = QLabel(self.centralwidget)
        self.dado4.setObjectName(u"dado4")
        self.dado4.setGeometry(QRect(210, 320, 91, 81))
        self.dado4.setScaledContents(True)
        self.dado5 = QLabel(self.centralwidget)
        self.dado5.setObjectName(u"dado5")
        self.dado5.setGeometry(QRect(120, 210, 101, 81))
        self.dado5.setScaledContents(True)
        self.lanzar_dados = QPushButton(self.centralwidget)
        self.lanzar_dados.setObjectName(u"lanzar_dados")
        self.lanzar_dados.setGeometry(QRect(40, 440, 281, 25))
        self.tabla_puntajes = QTableWidget(self.centralwidget)
        if (self.tabla_puntajes.columnCount() < 2):
            self.tabla_puntajes.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.tabla_puntajes.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tabla_puntajes.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        if (self.tabla_puntajes.rowCount() < 12):
            self.tabla_puntajes.setRowCount(12)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(0, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(1, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(2, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(3, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(4, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(5, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(6, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(7, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(8, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(9, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(10, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.tabla_puntajes.setVerticalHeaderItem(11, __qtablewidgetitem13)
        self.tabla_puntajes.setObjectName(u"tabla_puntajes")
        self.tabla_puntajes.setGeometry(QRect(470, 60, 321, 391))
        self.tabla_puntajes.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.jugador_actual = QLabel(self.centralwidget)
        self.jugador_actual.setObjectName(u"jugador_actual")
        self.jugador_actual.setGeometry(QRect(10, 0, 331, 51))
        font = QFont()
        font.setPointSize(18)
        self.jugador_actual.setFont(font)
        self.tiempo_restante = QLabel(self.centralwidget)
        self.tiempo_restante.setObjectName(u"tiempo_restante")
        self.tiempo_restante.setGeometry(QRect(470, 0, 321, 41))
        font1 = QFont()
        font1.setPointSize(17)
        self.tiempo_restante.setFont(font1)
        self.tiempo_restante.setStyleSheet(u"Tiempo_restante\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255));\n"
"font: 18pt \"Ubuntu\";")
        self.tiempo_restante.setScaledContents(False)
        self.escalera = QPushButton(self.centralwidget)
        self.escalera.setObjectName(u"escalera")
        self.escalera.setGeometry(QRect(370, 270, 89, 21))
        self.full = QPushButton(self.centralwidget)
        self.full.setObjectName(u"full")
        self.full.setGeometry(QRect(370, 300, 89, 21))
        self.poker = QPushButton(self.centralwidget)
        self.poker.setObjectName(u"poker")
        self.poker.setGeometry(QRect(370, 320, 91, 25))
        self.generala = QPushButton(self.centralwidget)
        self.generala.setObjectName(u"generala")
        self.generala.setGeometry(QRect(370, 350, 89, 25))
        self.generala_doble = QPushButton(self.centralwidget)
        self.generala_doble.setObjectName(u"generala_doble")
        self.generala_doble.setGeometry(QRect(340, 380, 121, 25))
        self.uno = QPushButton(self.centralwidget)
        self.uno.setObjectName(u"uno")
        self.uno.setGeometry(QRect(370, 90, 89, 21))
        self.dos = QPushButton(self.centralwidget)
        self.dos.setObjectName(u"dos")
        self.dos.setGeometry(QRect(370, 120, 89, 21))
        self.tres = QPushButton(self.centralwidget)
        self.tres.setObjectName(u"tres")
        self.tres.setGeometry(QRect(370, 150, 89, 25))
        self.cuatro = QPushButton(self.centralwidget)
        self.cuatro.setObjectName(u"cuatro")
        self.cuatro.setGeometry(QRect(370, 180, 89, 25))
        self.cinco = QPushButton(self.centralwidget)
        self.cinco.setObjectName(u"cinco")
        self.cinco.setGeometry(QRect(370, 210, 89, 25))
        self.seis = QPushButton(self.centralwidget)
        self.seis.setObjectName(u"seis")
        self.seis.setGeometry(QRect(370, 240, 89, 21))
        self.mensaje_final = QLabel(self.centralwidget)
        self.mensaje_final.setObjectName(u"mensaje_final")
        self.mensaje_final.setGeometry(QRect(230, 210, 67, 17))
        self.tirada1 = QLabel(self.centralwidget)
        self.tirada1.setObjectName(u"tirada1")
        self.tirada1.setEnabled(True)
        self.tirada1.setGeometry(QRect(40, 470, 81, 71))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.tirada1.sizePolicy().hasHeightForWidth())
        self.tirada1.setSizePolicy(sizePolicy)
        self.tirada1.setMinimumSize(QSize(30, 30))
        self.tirada1.setMaximumSize(QSize(16777215, 16777215))
        self.tirada1.setScaledContents(True)
        self.tirada2 = QLabel(self.centralwidget)
        self.tirada2.setObjectName(u"tirada2")
        self.tirada2.setGeometry(QRect(130, 470, 81, 71))
        sizePolicy.setHeightForWidth(self.tirada2.sizePolicy().hasHeightForWidth())
        self.tirada2.setSizePolicy(sizePolicy)
        self.tirada2.setMinimumSize(QSize(20, 20))
        self.tirada2.setScaledContents(True)
        self.tirada3 = QLabel(self.centralwidget)
        self.tirada3.setObjectName(u"tirada3")
        self.tirada3.setGeometry(QRect(230, 470, 81, 71))
        sizePolicy.setHeightForWidth(self.tirada3.sizePolicy().hasHeightForWidth())
        self.tirada3.setSizePolicy(sizePolicy)
        self.tirada3.setMinimumSize(QSize(20, 20))
        self.tirada3.setScaledContents(True)
        self.Tiradas_agotadas = QLabel(self.centralwidget)
        self.Tiradas_agotadas.setObjectName(u"Tiradas_agotadas")
        self.Tiradas_agotadas.setGeometry(QRect(476, 470, 311, 61))
        self.Tiradas_agotadas.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.lanzar_dados.setText(QCoreApplication.translate("MainWindow", u"Lanzar Dados", None))
        ___qtablewidgetitem = self.tabla_puntajes.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Jugador 1", None));
        ___qtablewidgetitem1 = self.tabla_puntajes.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Jugador 2", None));
        ___qtablewidgetitem2 = self.tabla_puntajes.verticalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"1", None));
        ___qtablewidgetitem3 = self.tabla_puntajes.verticalHeaderItem(1)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"2", None));
        ___qtablewidgetitem4 = self.tabla_puntajes.verticalHeaderItem(2)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"3", None));
        ___qtablewidgetitem5 = self.tabla_puntajes.verticalHeaderItem(3)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"4", None));
        ___qtablewidgetitem6 = self.tabla_puntajes.verticalHeaderItem(4)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"5", None));
        ___qtablewidgetitem7 = self.tabla_puntajes.verticalHeaderItem(5)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"6", None));
        ___qtablewidgetitem8 = self.tabla_puntajes.verticalHeaderItem(6)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Escalera", None));
        ___qtablewidgetitem9 = self.tabla_puntajes.verticalHeaderItem(7)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Full", None));
        ___qtablewidgetitem10 = self.tabla_puntajes.verticalHeaderItem(8)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"P\u00f3ker", None));
        ___qtablewidgetitem11 = self.tabla_puntajes.verticalHeaderItem(9)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Generala", None));
        ___qtablewidgetitem12 = self.tabla_puntajes.verticalHeaderItem(10)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"Generala Doble", None));
        ___qtablewidgetitem13 = self.tabla_puntajes.verticalHeaderItem(11)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"Puntuaci\u00f3n", None));
        self.jugador_actual.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#000000;\">Turno de:</span></p></body></html>", None))
        self.tiempo_restante.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Tiempo:</p></body></html>", None))
        self.escalera.setText(QCoreApplication.translate("MainWindow", u"Escalera", None))
        self.full.setText(QCoreApplication.translate("MainWindow", u"Full", None))
        self.poker.setText(QCoreApplication.translate("MainWindow", u"P\u00f3ker", None))
        self.generala.setText(QCoreApplication.translate("MainWindow", u"Generala", None))
        self.generala_doble.setText(QCoreApplication.translate("MainWindow", u"Generala Doble", None))
        self.uno.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.dos.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.tres.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.cuatro.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.cinco.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.seis.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.tirada1.setText("")
        self.tirada2.setText("")
        self.tirada3.setText("")
        self.Tiradas_agotadas.setText(QCoreApplication.translate("MainWindow", u"            Debes seleccionar una categor\u00eda!!!", None))
    # retranslateUi

